"""Emit the report's numbers as LaTeX, straight from the npz products.

Every number the report quotes is defined here as a macro or a table
row body, and the report ``\\input``s the result.  Nothing is typed
into the ``.tex`` by hand.

This exists because hand-transcription failed twice: the tail gate was
published comparing a truncated signal against a full-template
threshold, and the closed-form comparison was published as "within a
few percent" when it is 0.980 / 1.161 / 0.542.  Both were arithmetic
that had drifted from the products it claimed to summarise.  A
generated file cannot drift.

Writes ``report/faraday_depth_template/generated.tex``.

Cheap: seconds.  Needs the step5 npz products, no ``data/``.

Usage:
  uv run python step5_tables.py
"""

import common  # noqa: F401
import numpy as np

from common import GEN_DIR, REPO
from lusee_faraday import dispersion as dsp
from lusee_faraday.conventions import lambda_squared

OUT = REPO / "report" / "faraday_depth_template" / "generated.tex"
WORD = {30: "Thirty", 50: "Fifty", 10: "Ten"}
LINES = []


def macro(name, value):
    LINES.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def ratio(x):
    """Format a detection ratio without collapsing small ones to 0.000."""
    if x >= 1e-3:
        return f"{x:.3f}"
    return sci(x, 2)


def big(x):
    """Format a large factor readably."""
    return f"{x:.0f}" if x < 1e4 else sci(x, 2)


def sci(x, sig=3):
    """Scientific notation as \\ensuremath, e.g. 4.27x10^-4.

    \\ensuremath and NOT $...$: these macros are used both in table
    cells (text mode) and inside $...$ in the prose, and a macro that
    carries its own dollars produces "$$" in the second case, which is
    a "Missing $ inserted" fatal.
    """
    if x == 0:
        return "0"
    e = int(np.floor(np.log10(abs(x))))
    m = x / 10.0**e
    # Renormalise when the mantissa ROUNDS up through a decade: 9.98e-4
    # at sig=2 formats as "10.0x10^-4" otherwise, which is not
    # scientific notation.  floor(log10) cannot see this because it acts
    # before the rounding does.
    if abs(round(m, sig - 1)) >= 10.0:
        e += 1
        m = x / 10.0**e
    return f"\\ensuremath{{{m:.{sig - 1}f}\\times10^{{{e}}}}}"


def fwhm(x, y, level):
    """Interpolated full width at ``level`` x peak."""
    y = np.asarray(y, float) / np.max(y)
    i = int(np.argmax(y))

    def cross(step):
        j = i
        while 0 <= j + step < y.size and y[j + step] >= level:
            j += step
        x0, x1, y0, y1 = x[j], x[j + step], y[j], y[j + step]
        return x0 + (level - y0) * (x1 - x0) / (y1 - y0)

    return cross(+1) - cross(-1)


def main():
    d = np.load(GEN_DIR / "step5_template.npz")
    d2 = np.load(GEN_DIR / "step5_template_two_port.npz")
    env = np.load(GEN_DIR / "step5_envelope.npz")
    det = np.load(GEN_DIR / "step5_detection.npz")
    det2 = np.load(GEN_DIR / "step5_detection_two_port.npz")
    bands = [int(b) for b in d["bands"]]
    kf = int(d["k_fiducial_index"]) if "k_fiducial_index" in d.files else 1
    cuts = det["cuts"]
    ic0 = int(np.argmin(np.abs(cuts - 0.0)))
    ics = int(np.argmin(np.abs(cuts - 27.5)))  # the window-budget cut
    lun = int(det["lunations"])

    LINES.append("% GENERATED by scripts/step5_tables.py -- do not edit.")
    LINES.append("% Regenerate:  uv run python scripts/step5_tables.py")
    macro("Lunations", lun)
    macro("SafeCut", f"{cuts[ics]:.1f}")

    # ---------------------------------------------------- detection
    for ib, b in enumerate(bands):
        w = WORD[b]
        macro(f"detNoCutSlab{w}", f"{det['ratio_slab'][ib, ic0]:.1f}")
        macro(f"detNoCutDisp{w}", ratio(det["ratio_dispersion"][ib, ic0]))
        macro(f"detSafeSlab{w}", f"{det['ratio_slab'][ib, ics]:.1f}")
        macro(f"detSafeDisp{w}", ratio(det["ratio_dispersion"][ib, ics]))
        macro(f"keepFrac{w}", f"{100 * det['power_fraction'][ib, ics]:.0f}")
        macro(
            f"cutCost{w}",
            f"{det['ratio_slab'][ib, ic0] / det['ratio_slab'][ib, ics]:.1f}",
        )
        macro(f"tauSafe{w}", f"{det['tau_us'][ib, ics]:.1f}")
        macro(f"amfNoCut{w}", sci(det["a_mf"][ib, ic0]))
        macro(f"amfSafe{w}", sci(det["a_mf"][ib, ics]))
        macro(f"tailSlab{w}", f"{det['tail_corrected'][ib, 2]:.2f}")
        macro(f"tailSlabTwoPort{w}", f"{det2['tail_corrected'][ib, 2]:.2f}")
        macro(f"tailFrac{w}", f"{100 * det['tail_corrected'][ib, 0]:.2f}")
        # observing-time factor to close a dispersion-floor gap: with
        # n_lst saturated, A ~ n^-1/2, so the cost is the gap SQUARED.
        for tag, ic in (("NoCut", ic0), ("Safe", ics)):
            gap = 1.0 / max(det["ratio_dispersion"][ib, ic], 1e-300)
            macro(f"dispGap{tag}{w}", f"{gap:.1f}")
            macro(f"dispTime{tag}{w}", big(gap**2))

    rows = []
    for ic, cut in enumerate(cuts):
        if det["power_fraction"][:, ic].max() <= 0:
            continue
        cells = [
            "no cut" if cut == 0 else f"$\\geq {cut:g}$",
            f"{100 * det['power_fraction'][0, ic]:.0f}\\%",
        ]
        for ib in range(len(bands)):
            cells += [
                f"{det['ratio_slab'][ib, ic]:.1f}",
                ratio(det["ratio_dispersion"][ib, ic]),
            ]
        rows.append(" & ".join(cells) + r" \\")
    LINES.append(r"\newcommand{\DetectionRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ---------------------------------------------------- bracket
    rows = []
    for lvl, name in ((0, "upper"), (1, "slab"), (2, "disp")):
        cells = [
            {
                0: "$A_{\\rm upper}$",
                1: "$A_{\\rm slab}$",
                2: "$A_{\\rm disp}$",
            }[lvl]
        ]
        cells += [sci(d["bracket"][ib, lvl]) for ib in range(len(bands))]
        rows.append(" & ".join(cells) + r" \\")
        for ib, b in enumerate(bands):
            macro(
                f"bracket{name.capitalize()}{WORD[b]}",
                sci(d["bracket"][ib, lvl]),
            )
    LINES.append(r"\newcommand{\BracketRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ------------------------------------------------- slope (S4.11)
    # The two floors carry DIFFERENT spectral slopes -- nu^2 against
    # nu^4 -- so a RATIO between bands discriminates them needing no
    # absolute scale and no assumed intrinsic polarization fraction.
    # What is emitted is the calibration REQUIREMENT, not a capability:
    # a power law's slope carries its exponent, not its amplitude, and
    # the amplitude is degenerate with p_0 (S4.11.3).
    PAIR = {"FiftyThirty": "50/30", "ThirtyTen": "30/10"}
    rows = []
    for ilo, ihi, tag in ((0, 1, "FiftyThirty"), (2, 0, "ThirtyTen")):
        blo = {
            "lower_slab": float(d["bracket"][ilo, 1]),
            "lower_dispersion": float(d["bracket"][ilo, 2]),
        }
        bhi = {
            "lower_slab": float(d["bracket"][ihi, 1]),
            "lower_dispersion": float(d["bracket"][ihi, 2]),
        }
        # SNR at the SLAB floor.  The detection ratio is referred to the
        # 5-sigma amplitude, so SNR = 5 x ratio.  The dispersion floor
        # gets no entry on purpose: there is no detection there, hence
        # no ratio to take, and the branch in which the slope exists is
        # the branch in which the slab floor holds.
        snr_lo = 5.0 * float(det["ratio_slab"][ilo, ics])
        snr_hi = 5.0 * float(det["ratio_slab"][ihi, ics])
        l2lo = float(np.asarray(lambda_squared(bands[ilo]), float)[0])
        l2hi = float(np.asarray(lambda_squared(bands[ihi]), float)[0])
        nu2 = l2lo / l2hi
        r3 = dsp.slope_requirement(blo, bhi, snr_lo, snr_hi, n_sigma=3.0)
        r5 = dsp.slope_requirement(blo, bhi, snr_lo, snr_hi, n_sigma=5.0)
        macro(f"slopeSlab{tag}", f"{r5['ratio_slab']:.3f}")
        macro(f"slopeNuTwo{tag}", f"{nu2:.3f}")
        macro(f"slopeDisp{tag}", f"{r5['ratio_dispersion']:.3f}")
        macro(f"slopeNuFour{tag}", f"{nu2**2:.3f}")
        # Signed: a RISING beam-weighted phi_med pushes the slab ratio
        # BELOW nu^2, and the direction is the evidence that the drift
        # is physical and not a rounding artefact.
        macro(
            f"slopeDepartSlab{tag}",
            f"{100 * (r5['ratio_slab'] / nu2 - 1.0):+.1f}",
        )
        macro(
            f"slopeDepartDisp{tag}",
            f"{100 * (r5['ratio_dispersion'] / nu2**2 - 1.0):+.2f}",
        )
        macro(f"slopeSep{tag}", f"{r5['separation']:.2f}")
        macro(f"slopeStat{tag}", f"{100 * np.expm1(r5['sigma_stat']):.1f}")
        macro(f"slopeBudgetThree{tag}", f"{100 * r3['tolerance']:.0f}")
        macro(f"slopeBudgetFive{tag}", f"{100 * r5['tolerance']:.0f}")
        # Quoted as a FACTOR and not a percentage.  The budget lives in
        # log space and is asymmetric, so a "108%" 1-sigma fractional
        # error invites reading the gain as consistent with zero; the
        # multiplicative form exp(sigma_sys) says what it means and
        # does not break above 100%.  It is also how a gain
        # requirement is written down.
        f3, f5 = np.exp(r3["sigma_sys"]), np.exp(r5["sigma_sys"])
        macro(f"slopeFactorThree{tag}", f"{f3:.2f}")
        macro(f"slopeFactorFive{tag}", f"{f5:.2f}")
        rows.append(
            f"{PAIR[tag]}\\,MHz & {r5['ratio_slab']:.3f} ({nu2:.3f}) & "
            f"{r5['ratio_dispersion']:.3f} ({nu2**2:.3f}) & "
            f"{100 * np.expm1(r5['sigma_stat']):.1f}\\% & "
            f"{f3:.2f}$\\times$ & {f5:.2f}$\\times$ \\\\"
        )
    LINES.append(r"\newcommand{\SlopeRows}{%")
    LINES.extend(rows)
    LINES.append("}")
    for ib, b in enumerate(bands):
        macro(f"snrSlab{WORD[b]}", f"{5.0 * det['ratio_slab'][ib, ics]:.0f}")

    # ---------------------------------------------------- resolution
    rows = []
    for band, half in ((30.0, 40.0), (50.0, 150.0), (10.0, 2.0)):
        fine, bins, W = dsp.zoom_bin_matrix(band)
        po = np.linspace(-half, half, 80001)
        p = dsp.rmsf(0.0, fine, W, bins, po)
        dl2 = np.ptp(np.asarray(lambda_squared(bins), float))
        pw, am, th = (
            fwhm(po, p, 0.5),
            fwhm(po, p, 0.25),
            2 * 1.8955 / dl2,
        )
        rows.append(
            f"{band:.0f}\\,MHz & {pw:.3f} & \\textbf{{{am:.3f}}} & "
            f"{th:.3f} \\\\"
        )
        macro(f"resAmp{WORD[int(band)]}", f"{am:.3f}")
        macro(f"resPow{WORD[int(band)]}", f"{pw:.3f}")
        # How far the systematics cut sits from the origin, in
        # amplitude resolution elements.  This is what ranks the bands
        # for executing the cut, and it is basis-independent.
        macro(f"cutRes{WORD[int(band)]}", f"{cuts[ics] / am:.1f}")
    LINES.append(r"\newcommand{\ResolutionRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ---------------------------------------------------- horizons
    rows = []
    for ib, b in enumerate(env["bands"]):
        rows.append(
            f"{b:.0f}\\,MHz & {env['parent_horizon'][ib]:.2f} & "
            f"{env['zoom_horizon'][ib]:.1f} \\\\"
        )
        macro(f"parentHor{WORD[int(b)]}", f"{env['parent_horizon'][ib]:.2f}")
        macro(f"zoomHor{WORD[int(b)]}", f"{env['zoom_horizon'][ib]:.1f}")
    LINES.append(r"\newcommand{\HorizonRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    pct_names = ("pFifty", "pNinety", "pNineNine", "pNineNineNine")
    for nm, v in zip(pct_names, env["percentiles"]):
        macro(nm, f"{v:.1f}")
    macro("rmMax", f"{float(env['rm_max']):.1f}")

    # ---------------------------------------------------- robustness
    rows = []
    for ib, b in enumerate(bands):
        kn, kt = d["knee"][ib, kf], d["knee_taper"][ib, kf]
        k2 = d2["knee"][ib, kf]
        rows.append(
            f"{b}\\,MHz & {kn:.2f} & {kt:.2f} & {kn / kt:.2f}$\\times$ & "
            f"{k2:.2f} & {100 * (k2 - kn) / kn:+.1f}\\% \\\\"
        )
        macro(f"knee{WORD[b]}", f"{kn:.1f}")
        macro(f"taperFactor{WORD[b]}", f"{kn / kt:.2f}")
        macro(f"armSwap{WORD[b]}", f"{100 * (k2 - kn) / kn:+.1f}")
    LINES.append(r"\newcommand{\RobustnessRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ------------------------------------------- the two bases
    C_LIGHT = 299792458.0
    rows = []
    for ib, b in enumerate(bands):
        _, bins, _ = dsp.zoom_bin_matrix(float(b))
        dt = 1.0 / ((bins.max() - bins.min()) * 1e6)
        nyq = 1.0 / (2 * np.median(np.diff(np.sort(bins))) * 1e6)
        alias = nyq * np.pi * (b * 1e6) ** 3 / (2 * C_LIGHT**2)
        tau_max = (
            2 * float(env["rm_max"]) * C_LIGHT**2 / (np.pi * (b * 1e6) ** 3)
        )
        ext = tau_max / dt
        smear = tau_max * 3 * 0.2e6 / (b * 1e6) / dt
        H = d["H"][ib, kf]
        al = H[d["phi"] > alias].sum() / H.sum()
        keep = det["power_fraction"][ib, ics]
        rows.append(
            f"{b}\\,MHz & {ext:.0f} & {smear:.1f} & "
            f"\\textbf{{{100 * smear / ext:.1f}\\%}} & {alias:.0f} & "
            f"{100 * al / keep:.1f}\\% \\\\"
        )
        macro(f"chirpPct{WORD[b]}", f"{100 * smear / ext:.1f}")
        macro(f"aliasPct{WORD[b]}", f"{100 * al / keep:.1f}")
        macro(f"aliasWall{WORD[b]}", f"{alias:.0f}")
        macro(f"zoomHorFromNyq{WORD[b]}", f"{alias:.1f}")
    LINES.append(r"\newcommand{\BasisRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ----------------------------------------- the pushforward itself
    # The geometry knob as an intermediate product: what the f^k
    # pushforward DOES to the map's own histogram, and how much the
    # deliverable depends on where in the family you sit.  Both come
    # from the committed templates; the scan is a re-analysis of them
    # (scripts/step5_kscan.py), pinned there against this same
    # detection product.
    ki = int(np.argmax(np.where(np.isfinite(d["ks"]), d["ks"], np.inf)))
    kd = int(np.argmin(d["ks"]))
    phi = d["phi"]
    ib0 = int(np.argmin(np.abs(np.array(bands) - 30)))  # the lead band
    rows = []
    for lo, hi in (
        (0, 1),
        (1, 3),
        (3, 10),
        (10, 30),
        (30, 100),
        (100, 300),
        (300, 1000),
        (1000, 2500),
    ):
        m = (phi >= lo) & (phi < hi)
        cells = [f"${lo}$--${hi}$"] + [
            f"{d['H'][ib0, ik][m].sum():.4f}" for ik in (ki, kf, kd)
        ]
        rows.append(" & ".join(cells) + r" \\")
    rows.append(r"\midrule")
    rows.append(
        "total & "
        + " & ".join(f"{d['H'][ib0, ik].sum():.4f}" for ik in (ki, kf, kd))
        + r" \\"
    )
    LINES.append(r"\newcommand{\MassRows}{%")
    LINES.extend(rows)
    LINES.append("}")
    macro("MassBand", f"{bands[ib0]}")
    # The factor between the two depolarisation floors, so the report
    # can set the geometry systematic against it without typing either.
    for ib, b in enumerate(bands):
        macro(
            f"floorRatio{WORD[b]}",
            big(d["bracket"][ib, 1] / d["bracket"][ib, 2]),
        )
    macro("MassZeroBinInf", f"{100 * d['H'][ib0, ki][0]:.1f}")
    macro("MassZeroBinFid", f"{100 * d['H'][ib0, kf][0]:.1f}")

    ksc_path = GEN_DIR / "step5_kscan.npz"
    if ksc_path.exists():
        ksc = np.load(ksc_path)
        kg, kcuts = ksc["ks"], ksc["cuts"]
        icut = int(np.argmin(np.abs(kcuts - float(ksc["safe_cut"]))))
        i0 = int(np.argmin(np.abs(kg)))  # k = 0
        ilo = int(np.argmin(np.abs(kg + 0.9)))  # k = -0.9
        macro("kscanKLow", f"{kg[ilo]:.2f}")
        macro("tiltThetaCDeg", f"{np.degrees(float(ksc['theta_c'][0])):.3f}")
        macro(
            "tiltThetaCClamped",
            "yes" if bool(np.all(ksc["theta_c_clamped"])) else "no",
        )
        # the nside-512 pixel scale theta_c has to beat to be resolvable
        macro(
            "pixelScaleDeg",
            f"{np.degrees(np.sqrt(4 * np.pi / (12 * 512.0**2))):.3f}",
        )
        macro("kscanKMax", f"{kg[-1]:.0f}")
        for ib, b in enumerate(bands):
            w = WORD[b]
            f0 = ksc["power_fraction"][ib, icut, i0]
            flo = ksc["power_fraction"][ib, icut, ilo]
            finf = ksc["power_fraction_kinf"][ib, icut]
            macro(f"kscanFZero{w}", f"{f0:.3f}")
            macro(f"kscanFLow{w}", f"{flo:.3f}")
            macro(f"kscanFInf{w}", f"{finf:.3f}")
            # the defensible half of the family costs this in POWER ...
            macro(f"kscanSpanHi{w}", f"{finf / f0:.2f}")
            # ... which is this in AMPLITUDE, hence in detection ratio
            macro(f"kscanAmp{w}", f"{np.sqrt(finf / f0):.2f}")
            macro(f"kscanSpanLo{w}", f"{f0 / flo:.2f}")
            macro(f"kscanKneeZero{w}", f"{ksc['knee'][ib, i0]:.0f}")
            macro(f"kscanKneeInf{w}", f"{ksc['knee_kinf'][ib]:.0f}")
            macro(f"kscanKS{w}", sci(ksc["validation"][ib, 0], 2))
            # The deliverable across the family.  RatioZero must equal
            # the detection table's detSafeSlab -- the scan recomputes
            # it from the k=inf histogram by an independent path, so a
            # disagreement means one of the two has drifted.
            macro(f"kscanRatioZero{w}", f"{ksc['ratio_slab'][ib, i0]:.1f}")
            macro(f"kscanRatioInf{w}", f"{ksc['ratio_slab_kinf'][ib]:.1f}")
            # The coherent limit, quantified rather than drawn: it is
            # the shape-space sibling of A_upper and inherits the same
            # theta_c disqualification, so the report states it in
            # "what this map cannot decide" and nowhere else.
            macro(f"tiltFrac{w}", f"{ksc['tilt'][ib, 0]:.3f}")
            macro(f"tiltRatio{w}", f"{ksc['tilt'][ib, 1]:.2f}")
            macro(f"tiltKnee{w}", f"{ksc['tilt'][ib, 2]:.0f}")
            # Convention-safe: folded/folded, so the signed fix cancels.
            fac = float(ksc["tilt"][ib, 3])
            macro(f"tiltFactor{w}", f"{fac:.2f}")
            macro(f"tiltApplied{w}", f"{ksc['ratio_slab'][ib, i0] / fac:.1f}")
            macro(f"kscanSqueeze{w}", f"{ksc['squeeze'][ib, 0]:.2f}")
            macro(f"kscanSqueezeKS{w}", f"{ksc['squeeze'][ib, 1]:.3f}")
            macro(f"kscanRawKS{w}", f"{ksc['squeeze'][ib, 2]:.3f}")

    # ------------------------------------------- intuition / caveats
    # scripts/step5_intuition.py; figures-and-caveats quantities that
    # need data/ and so cannot be computed in step5_plots.py.
    q_path = GEN_DIR / "step5_intuition.npz"
    if q_path.exists():
        q = np.load(q_path)
        names = ["Constant", "TwoValued", "GaussianSky", "Hutschenreuter"]
        for i, nm in enumerate(names):
            macro(f"cv{nm}", f"{q['toy_cv'][i]:.2f}")
        # the pushforward's variance ratio; -> 1/3 for a heavy tail
        vr = q["toy_var"][3, 1] / q["toy_var"][3, 0]
        macro("cvVarRatioHutschenreuter", f"{vr:.3f}")
        macro("betaShift", sci(float(q["beta_shift"]), 2))
        # The random-walk argument's own input.  It was asserted as
        # "order 1e3 rad/m^2" and is actually ~0.6; generated so it
        # cannot drift again.
        macro("adjMedian", f"{float(q['adj_median']):.2f}")
        macro("adjPninety", f"{float(q['adj_p90']):.1f}")
        for i, w in enumerate(("Ten", "Thirty", "Fifty")):
            macro(f"adjTurns{w}", f"{q['adj_turns'][i]:.0f}")
        macro("cohValidMHz", f"{float(q['coherent_valid_above_mhz']):.0f}")
        macro("rmStdMedian", f"{float(q['rm_std_median']):.1f}")
        macro("rmAbsMedian", f"{float(q['rm_abs_median']):.1f}")
        rm_pct = 100 * float(q["rm_std_median"]) / float(q["rm_abs_median"])
        macro("rmStdPct", f"{rm_pct:.0f}")
        # sensitivity of S to each input we do not control
        for nm, key in (("KInf", 0), ("RmSigma", 1), ("TwoPort", 2)):
            dm = np.abs(q["S_variants"][key] - q["S_fiducial"]).max()
            macro(f"dS{nm}", f"{dm:.3f}")
        # the Crab
        macro("crabSep", f"{float(q['pol_max_sep_deg']):.3f}")
        macro("crabSkyPct", f"{q['crab'][0]:.4f}")
        macro("crabWeightPct", f"{q['crab'][1]:.2f}")
        macro("crabContrast", f"{q['crab'][2]:.1f}")
        macro("crabExcess", f"{q['crab_excess'][0]:.2f}")
        macro("crabExcised", f"{q['crab_excess'][1]:.2f}")
        macro("weightConc", f"{float(q['weight_concentration']):.1f}")
        cd = q["crab_deliverable"]
        macro("crabRatioPct", f"{100 * (cd[1][0] / cd[0][0] - 1):+.1f}")
        macro("crabKneePct", f"{100 * (cd[1][1] / cd[0][1] - 1):+.1f}")
        # sigma_eff's missing effect on the SHAPE (report sec:sigmashape)
        macro("sigmaBroadenOne", f"{q['sigma_broaden_pct'][0]:.0f}")
        macro("sigmaBroadenTwo", f"{q['sigma_broaden_pct'][1]:.0f}")
        macro("sigmaEff", f"{float(d['sigma_eff']):.1f}")
        # the matched filter's real dimensionality
        macro("nEffModes", f"{float(q['n_eff_modes']):.0f}")
        macro("diagPenalty", f"{float(q['diag_noise_penalty']):.3f}")

    # ---------------------------------------------------- caveats
    macro("thetaCDeg", f"{np.degrees(float(d['theta_c'][0])):.1f}")
    macro(
        "thetaCAllClamped",
        "yes" if bool(np.all(d["theta_c_clamped"])) else "no",
    )
    s = np.load(GEN_DIR / "step5_sensitivity.npz")
    for ib, b in enumerate(s["bands"]):
        macro(f"tsys{WORD[int(b)]}", f"{s['tsys_over_tsky'][ib]:.4f}")
    macro(
        "tsysMaxPct",
        f"{100 * (np.max(s['tsys_over_tsky']) - 1.0):.1f}",
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(LINES) + "\n")
    n = sum(1 for ln in LINES if ln.startswith("\\newcommand"))
    print(f"wrote {OUT}  ({n} macros, {len(LINES)} lines)")


if __name__ == "__main__":
    main()
