"""Emit the report's numbers as LaTeX, straight from the npz products.

Every number the report quotes is defined here as a macro or a table
row body, and the report ``\\input``s the result.  Nothing is typed
into the ``.tex`` by hand.

This exists because hand-transcription failed twice: the tail gate was
published comparing a truncated signal against a full-template
threshold, and the closed-form comparison was published as "within a
few percent" when it is 0.980 / 1.161 / 0.542.  Both were arithmetic
that had drifted from the products it claimed to summarise.  A
generated file cannot drift.

Writes ``report/faraday_depth_template/generated.tex``.

Cheap: seconds.  Needs the step5 npz products, no ``data/``.

Usage:
  uv run python step5_tables.py
"""

import common  # noqa: F401
import numpy as np

from common import GEN_DIR, REPO
from lusee_faraday import dispersion as dsp
from lusee_faraday.conventions import lambda_squared

OUT = REPO / "report" / "faraday_depth_template" / "generated.tex"
WORD = {30: "Thirty", 50: "Fifty", 10: "Ten"}
LINES = []


def macro(name, value):
    LINES.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def ratio(x):
    """Format a detection ratio without collapsing small ones to 0.000."""
    if x >= 1e-3:
        return f"{x:.3f}"
    return sci(x, 2)


def big(x):
    """Format a large factor readably."""
    return f"{x:.0f}" if x < 1e4 else sci(x, 2)


def sci(x, sig=3):
    """Scientific notation as \\ensuremath, e.g. 4.27x10^-4.

    \\ensuremath and NOT $...$: these macros are used both in table
    cells (text mode) and inside $...$ in the prose, and a macro that
    carries its own dollars produces "$$" in the second case, which is
    a "Missing $ inserted" fatal.
    """
    if x == 0:
        return "0"
    e = int(np.floor(np.log10(abs(x))))
    m = x / 10.0**e
    return f"\\ensuremath{{{m:.{sig - 1}f}\\times10^{{{e}}}}}"


def fwhm(x, y, level):
    """Interpolated full width at ``level`` x peak."""
    y = np.asarray(y, float) / np.max(y)
    i = int(np.argmax(y))

    def cross(step):
        j = i
        while 0 <= j + step < y.size and y[j + step] >= level:
            j += step
        x0, x1, y0, y1 = x[j], x[j + step], y[j], y[j + step]
        return x0 + (level - y0) * (x1 - x0) / (y1 - y0)

    return cross(+1) - cross(-1)


def main():
    d = np.load(GEN_DIR / "step5_template.npz")
    d2 = np.load(GEN_DIR / "step5_template_two_port.npz")
    env = np.load(GEN_DIR / "step5_envelope.npz")
    det = np.load(GEN_DIR / "step5_detection.npz")
    det2 = np.load(GEN_DIR / "step5_detection_two_port.npz")
    bands = [int(b) for b in d["bands"]]
    kf = int(d["k_fiducial_index"]) if "k_fiducial_index" in d.files else 1
    cuts = det["cuts"]
    ic0 = int(np.argmin(np.abs(cuts - 0.0)))
    ics = int(np.argmin(np.abs(cuts - 27.5)))  # the window-budget cut
    lun = int(det["lunations"])

    LINES.append("% GENERATED by scripts/step5_tables.py -- do not edit.")
    LINES.append("% Regenerate:  uv run python scripts/step5_tables.py")
    macro("Lunations", lun)
    macro("SafeCut", f"{cuts[ics]:.1f}")

    # ---------------------------------------------------- detection
    for ib, b in enumerate(bands):
        w = WORD[b]
        macro(f"detNoCutSlab{w}", f"{det['ratio_slab'][ib, ic0]:.1f}")
        macro(f"detNoCutDisp{w}", ratio(det["ratio_dispersion"][ib, ic0]))
        macro(f"detSafeSlab{w}", f"{det['ratio_slab'][ib, ics]:.1f}")
        macro(f"detSafeDisp{w}", ratio(det["ratio_dispersion"][ib, ics]))
        macro(f"keepFrac{w}", f"{100 * det['power_fraction'][ib, ics]:.0f}")
        macro(
            f"cutCost{w}",
            f"{det['ratio_slab'][ib, ic0] / det['ratio_slab'][ib, ics]:.1f}",
        )
        macro(f"tauSafe{w}", f"{det['tau_us'][ib, ics]:.1f}")
        macro(f"amfNoCut{w}", sci(det["a_mf"][ib, ic0]))
        macro(f"amfSafe{w}", sci(det["a_mf"][ib, ics]))
        macro(f"tailSlab{w}", f"{det['tail_corrected'][ib, 2]:.2f}")
        macro(f"tailSlabTwoPort{w}", f"{det2['tail_corrected'][ib, 2]:.2f}")
        macro(f"tailFrac{w}", f"{100 * det['tail_corrected'][ib, 0]:.2f}")
        # observing-time factor to close a dispersion-floor gap: with
        # n_lst saturated, A ~ n^-1/2, so the cost is the gap SQUARED.
        for tag, ic in (("NoCut", ic0), ("Safe", ics)):
            gap = 1.0 / max(det["ratio_dispersion"][ib, ic], 1e-300)
            macro(f"dispGap{tag}{w}", f"{gap:.1f}")
            macro(f"dispTime{tag}{w}", big(gap**2))

    rows = []
    for ic, cut in enumerate(cuts):
        if det["power_fraction"][:, ic].max() <= 0:
            continue
        cells = [
            "no cut" if cut == 0 else f"$\\geq {cut:g}$",
            f"{100 * det['power_fraction'][0, ic]:.0f}\\%",
        ]
        for ib in range(len(bands)):
            cells += [
                f"{det['ratio_slab'][ib, ic]:.1f}",
                ratio(det["ratio_dispersion"][ib, ic]),
            ]
        rows.append(" & ".join(cells) + r" \\")
    LINES.append(r"\newcommand{\DetectionRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ---------------------------------------------------- bracket
    rows = []
    for lvl, name in ((0, "upper"), (1, "slab"), (2, "disp")):
        cells = [
            {
                0: "$A_{\\rm upper}$",
                1: "$A_{\\rm slab}$",
                2: "$A_{\\rm disp}$",
            }[lvl]
        ]
        cells += [sci(d["bracket"][ib, lvl]) for ib in range(len(bands))]
        rows.append(" & ".join(cells) + r" \\")
        for ib, b in enumerate(bands):
            macro(
                f"bracket{name.capitalize()}{WORD[b]}",
                sci(d["bracket"][ib, lvl]),
            )
    LINES.append(r"\newcommand{\BracketRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ---------------------------------------------------- resolution
    rows = []
    for band, half in ((30.0, 40.0), (50.0, 150.0), (10.0, 2.0)):
        fine, bins, W = dsp.zoom_bin_matrix(band)
        po = np.linspace(-half, half, 80001)
        p = dsp.rmsf(0.0, fine, W, bins, po)
        dl2 = np.ptp(np.asarray(lambda_squared(bins), float))
        pw, am, th = (
            fwhm(po, p, 0.5),
            fwhm(po, p, 0.25),
            2 * 1.8955 / dl2,
        )
        rows.append(
            f"{band:.0f}\\,MHz & {pw:.3f} & \\textbf{{{am:.3f}}} & "
            f"{th:.3f} \\\\"
        )
        macro(f"resAmp{WORD[int(band)]}", f"{am:.3f}")
        macro(f"resPow{WORD[int(band)]}", f"{pw:.3f}")
        # How far the systematics cut sits from the origin, in
        # amplitude resolution elements.  This is what ranks the bands
        # for executing the cut, and it is basis-independent.
        macro(f"cutRes{WORD[int(band)]}", f"{cuts[ics] / am:.1f}")
    LINES.append(r"\newcommand{\ResolutionRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ---------------------------------------------------- horizons
    rows = []
    for ib, b in enumerate(env["bands"]):
        rows.append(
            f"{b:.0f}\\,MHz & {env['parent_horizon'][ib]:.2f} & "
            f"{env['zoom_horizon'][ib]:.1f} \\\\"
        )
        macro(f"parentHor{WORD[int(b)]}", f"{env['parent_horizon'][ib]:.2f}")
        macro(f"zoomHor{WORD[int(b)]}", f"{env['zoom_horizon'][ib]:.1f}")
    LINES.append(r"\newcommand{\HorizonRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    pct_names = ("pFifty", "pNinety", "pNineNine", "pNineNineNine")
    for nm, v in zip(pct_names, env["percentiles"]):
        macro(nm, f"{v:.1f}")
    macro("rmMax", f"{float(env['rm_max']):.1f}")

    # ---------------------------------------------------- robustness
    rows = []
    for ib, b in enumerate(bands):
        kn, kt = d["knee"][ib, kf], d["knee_taper"][ib, kf]
        k2 = d2["knee"][ib, kf]
        rows.append(
            f"{b}\\,MHz & {kn:.2f} & {kt:.2f} & {kn / kt:.2f}$\\times$ & "
            f"{k2:.2f} & {100 * (k2 - kn) / kn:+.1f}\\% \\\\"
        )
        macro(f"knee{WORD[b]}", f"{kn:.1f}")
        macro(f"taperFactor{WORD[b]}", f"{kn / kt:.2f}")
        macro(f"armSwap{WORD[b]}", f"{100 * (k2 - kn) / kn:+.1f}")
    LINES.append(r"\newcommand{\RobustnessRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ------------------------------------------- the two bases
    C_LIGHT = 299792458.0
    rows = []
    for ib, b in enumerate(bands):
        _, bins, _ = dsp.zoom_bin_matrix(float(b))
        dt = 1.0 / ((bins.max() - bins.min()) * 1e6)
        nyq = 1.0 / (2 * np.median(np.diff(np.sort(bins))) * 1e6)
        alias = nyq * np.pi * (b * 1e6) ** 3 / (2 * C_LIGHT**2)
        tau_max = (
            2 * float(env["rm_max"]) * C_LIGHT**2 / (np.pi * (b * 1e6) ** 3)
        )
        ext = tau_max / dt
        smear = tau_max * 3 * 0.2e6 / (b * 1e6) / dt
        H = d["H"][ib, kf]
        al = H[d["phi"] > alias].sum() / H.sum()
        keep = det["power_fraction"][ib, ics]
        rows.append(
            f"{b}\\,MHz & {ext:.0f} & {smear:.1f} & "
            f"\\textbf{{{100 * smear / ext:.1f}\\%}} & {alias:.0f} & "
            f"{100 * al / keep:.1f}\\% \\\\"
        )
        macro(f"chirpPct{WORD[b]}", f"{100 * smear / ext:.1f}")
        macro(f"aliasPct{WORD[b]}", f"{100 * al / keep:.1f}")
        macro(f"aliasWall{WORD[b]}", f"{alias:.0f}")
        macro(f"zoomHorFromNyq{WORD[b]}", f"{alias:.1f}")
    LINES.append(r"\newcommand{\BasisRows}{%")
    LINES.extend(rows)
    LINES.append("}")

    # ---------------------------------------------------- caveats
    macro("thetaCDeg", f"{np.degrees(float(d['theta_c'][0])):.1f}")
    macro(
        "thetaCAllClamped",
        "yes" if bool(np.all(d["theta_c_clamped"])) else "no",
    )
    s = np.load(GEN_DIR / "step5_sensitivity.npz")
    for ib, b in enumerate(s["bands"]):
        macro(f"tsys{WORD[int(b)]}", f"{s['tsys_over_tsky'][ib]:.4f}")
    macro(
        "tsysMaxPct",
        f"{100 * (np.max(s['tsys_over_tsky']) - 1.0):.1f}",
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(LINES) + "\n")
    n = sum(1 for ln in LINES if ln.startswith("\\newcommand"))
    print(f"wrote {OUT}  ({n} macros, {len(LINES)} lines)")


if __name__ == "__main__":
    main()
